# Generated by Django 4.1.1 on 2022-10-16 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category4',
            old_name='parentid',
            new_name='parent',
        ),
    ]
