# Generated by Django 4.1.1 on 2022-10-16 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_parentid_category4_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.category4')),
            ],
        ),
    ]
