# Generated by Django 4.1.1 on 2022-10-16 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_products4'),
    ]

    operations = [
        migrations.AddField(
            model_name='products4',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='products4',
            name='image',
            field=models.ImageField(default='0000000', upload_to='uploads/products/'),
        ),
        migrations.AddField(
            model_name='products4',
            name='image1',
            field=models.ImageField(default='0000000', upload_to='uploads/products/'),
        ),
        migrations.CreateModel(
            name='Products3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('image', models.ImageField(default='0000000', upload_to='uploads/products/')),
                ('image1', models.ImageField(default='0000000', upload_to='uploads/products/')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.category4')),
            ],
        ),
    ]
