# Generated by Django 4.1.1 on 2022-10-16 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_products4_description_products4_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products4',
            new_name='Products6',
        ),
        migrations.CreateModel(
            name='Category6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category6')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='products6',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.category6'),
        ),
    ]
