# Generated by Django 4.1.1 on 2022-10-17 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_products4_products6_category6_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category6',
            name='dispname',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
