# Generated by Django 4.1.1 on 2022-10-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_category6_dispname'),
    ]

    operations = [
        migrations.CreateModel(
            name='multimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multimage', models.ImageField(blank=True, null=True, upload_to='multi/image')),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
    ]
