# Generated by Django 4.1.1 on 2022-10-17 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_multimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimage',
            name='price',
        ),
        migrations.AlterField(
            model_name='multimage',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.products6'),
        ),
    ]
