# Generated by Django 4.1.1 on 2022-10-17 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_multimage_price_alter_multimage_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multimage',
            old_name='category',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='products6',
            name='price',
        ),
    ]
