# Generated by Django 4.1.1 on 2022-10-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_category_multimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products6',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
