# Generated by Django 4.1.1 on 2022-10-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_products6_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products3',
        ),
    ]
