# Generated by Django 4.1.1 on 2022-10-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_products3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category2',
            name='parentid',
        ),
        migrations.RemoveField(
            model_name='category3',
            name='parentid',
        ),
        migrations.RemoveField(
            model_name='category4',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='addrress1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='addrress2',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='addrress3',
            new_name='address3',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.products6'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category2',
        ),
        migrations.DeleteModel(
            name='Category3',
        ),
        migrations.DeleteModel(
            name='Category4',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
